name: build release

on:
  push:
    tags:
      - "*"

jobs:
  build_release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Erlang
        uses: erlef/setup-beam@v1
        with:
          version-file: emqx-plugin-templates/.tool-versions
          version-type: strict
      - name: Install rebar3 template
        run: make install-rebar-template
      - name: build plugins
        run: |
          ./scripts/build-sample-plugin.sh --tag ${{ github.ref_name }} --name my_emqx_plugin_avsc --with-avsc --output-dir build
          ./scripts/build-sample-plugin.sh --tag ${{ github.ref_name }} --name my_emqx_plugin --output-dir build
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            build/*.tar.gz

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
      - build_release
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: packages
          path: packages
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: EMQX5 Example Plugin ${{ github.ref_name }} Released
          body: EMQX5 Example Plugin ${{ github.ref_name }} Released
          draft: false
          prerelease: false
      - uses: Rory-Z/upload-release-asset@v1
        with:
          repo: emqx-plugin-template
          path: "packages/*.tar.gz"
          token: ${{ github.token }}
