name: build release

on:
  push:
    tags:
      - "*"

jobs:
  build_release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/emqx/emqx-builder/5.4-4:1.17.3-27.2-2-ubuntu24.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup rebar3 template
        run: |
          git config --global --add safe.directory "$(pwd)"
          mkdir -p ~/.config/rebar3/templates
          cp -r . ~/.config/rebar3/templates

      - name: build plugins
        run: |
          mkdir -p build
          ./build_sample_plugin.sh --tag ${{ github.ref_name }} --name my_emqx_plugin_avsc --with-avsc --output-dir build
          ./build_sample_plugin.sh --tag ${{ github.ref_name }} --name my_emqx_plugin --output-dir build
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            build/*.tar.gz

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
      - build_release
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: packages
          path: packages
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: EMQX5 Example Plugin ${{ github.ref_name }} Released
          body: EMQX5 Example Plugin ${{ github.ref_name }} Released
          draft: false
          prerelease: false
      - uses: Rory-Z/upload-release-asset@v1
        with:
          repo: emqx-plugin-template
          path: "packages/*.tar.gz"
          token: ${{ github.token }}
